### PR TITLE
API for user-controlled events

### PR DESCRIPTION
**Pull request by amasad**
Based on @arichiardi's work in #81. This introduces a way to set
custom key handlers:

* key press handler: concerned with text input
* control key handler: concerned with other key handler

The handlers can return false to prevent jqconsole from handling the
event.

jq_console_auto_complete mov

### CODE REVIEW

**Comment by amasad** [comment]
Any other comments. I think this is a powerful and simple API

**Comment by arichiardi** [comment]
I like it!

**Comment by amasad** [comment]
Can I remove the `CLASS_USER_TEXT`?

**Comment by arichiardi** [comment]
Yes but is there an altrrnative way to identify that part of the text for styling it, for instance with highlight.js? I mean the text in $prompt.left

**Comment by arichiardi** [comment]
In particular I am using something similar to:

hljs.configure({useBR: true});

$('jqconsole-user-text').each(function(i, block) {
  hljs.highlightBlock(block);
});

But maybe ther's a better approach I am missing...

**Comment by amasad** [comment]
I can keep it. But it only gives you the left of the cursor. I can make all parts of the prompt a `.jqconsole-prompt-text` class?

**Comment by arichiardi** [comment]
Usually you want to highlight the user text, but I will try you patch and report back

**Comment by amasad** [comment]
It's still use text. Prompt left only captures the text on the current line
left of the cursor. The new class is added to all possible use text

**Comment by arichiardi** [comment]
No, it  does not work, because the call do `hljs.highlightBlock(block);` before the text being pushed in `$prompt_left`. It is basically a "post" event I need, an event that is triggered after the `$prompt_left` span is updated. My initial idea for using the `keypress` event was wrong (told you I am not a js expert) but I am glad we found a way to implement auto-completion.

**Comment by arichiardi** [comment]
Another thing I could do is to return false from the `keypress` handler and then write my self the prompt. A bit like you do with `.Write` using ANSI. I have a lib for stylize `clojure` forms. Or use lower level API from highlight js.

**Comment by arichiardi** [comment]
But still, I would prefer to have one class for that specific part of the prompt. I also found a bug as you can see in the comment to your commit.

**Comment by amasad** [comment]
Sure send a PR and I'll happily accept

**Pull request merged**
